# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: setup yarn
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install yarn
        yarn --version

    - name: build vuepress
      working-directory: mydocs
      run: |
        yarn
        yarn build
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        # GitHub repository where assets will be deployed (default current)
        #repo: # optional
        # Git branch where assets will be deployed
        #target_branch: # optional, default is gh-pages
        # Create incremental commit instead of doing push force
        #keep_history: # optional, default is false
        # Allow an empty commit to be created
        #allow_empty_commit: # optional, default is true
        # Build directory to deploy
        build_dir: mydocs/docs/.vuepress/dist/
        # The committer name and email address
        #committer: # optional
        # The author name and email address
        #author: # optional
        # Commit message
        #commit_message: # optional
        # Write the given domain name to the CNAME file
        #fqdn: # optional
        # Allow Jekyll to build your site
        jekyll: false # optional, default is true
        
#     - name: deploy vuepress
#       uses: jenkey2011/vuepress-deploy@1.0.1
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BUILD_SCRIPT: yarn --version
#         BUILD_DIR: mydocs/docs/.vuepress/dist/
#         TARGET_BRANCH: gh-pages

