on: [workflow_dispatch]

jobs:
  register_iot_job:
    runs-on: ubuntu-latest
    name: A job to register an IoT Edge Device on Azure IoT Hub
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Register step
      id: register
      uses: rdlucas2/actionsHackathonSubmissions@v0.0.9
      with:
        azure-sp-client-id: '${{ secrets.AZ_SP_CLIENTID }}'
        azure-sp-password: '${{ secrets.AZ_SP_PASSWORD }}'
        azure-tenant-id: '${{ secrets.AZ_TENANT }}'
        #azure-iot-device-id: 'MyNewDevice2'
        azure-iot-hub-name: '${{ secrets.AZ_IOT_HUB_NAME }}'
        device-list-file-path: '/github/workspace/devices/list.txt'
