on: [workflow_dispatch]

jobs:
  register_iot_job:
    runs-on: ubuntu-latest
    name: A job to register an IoT Edge Device on Azure IoT Hub
    steps:
    - name: Register step
      id: register
      uses: rdlucas2/actionsHackathonSubmissions@v3